# Generated by Django 4.1.3 on 2023-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_women_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.CharField(db_index=True, max_length=100)),
                ('user_2', models.CharField(db_index=True, default='не визначений', max_length=100)),
                ('score_1', models.IntegerField(default=0)),
                ('score_2', models.IntegerField(default=0)),
                ('name_1', models.CharField(db_index=True, default=0, max_length=100)),
                ('name_2', models.CharField(db_index=True, default=0, max_length=100)),
                ('name_3', models.CharField(db_index=True, default=0, max_length=100)),
                ('year_1', models.IntegerField(default=0)),
                ('year_2', models.IntegerField(default=0)),
                ('year_3', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
