# Generated by Django 4.1.3 on 2023-02-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_gameroom_attempt_1_gameroom_attempt_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='winner',
            field=models.CharField(db_index=True, default='нема', max_length=100),
        ),
    ]
