# Generated by Django 4.1.3 on 2023-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_gameroom_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.CharField(db_index=True, max_length=100)),
                ('user_2', models.CharField(db_index=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time_update'],
            },
        ),
        migrations.AlterModelOptions(
            name='gameroom',
            options={'ordering': ['-time_create']},
        ),
    ]
